#!/usr/bin/env bash
# Noderyx Framework: deploy this application from GitHub, on cPanel.
#
#   bash ~/public_html/deployment/deploy.sh
#
# Fetches the configured branch, replaces the application files, installs
# dependencies when package.json changed, and restarts the application.
#
# Files that belong to this server are never replaced:
#   .env  .htaccess  tmp/  node_modules/  deployment/deploy.config
#   storage/  public/uploads/  and anything added to KEEP in deploy.config.
#
# Commands:
#   deploy      Default. Fetch, sync, install, restart.
#   init        Write deployment/deploy.config so this account keeps its own
#               repository, branch, and token.
#   status      Print what is configured and what the last deploy did.
#   install     Install dependencies only.
#   restart     Restart the application only.
#   rollback    Restore the snapshot taken before the last deploy.
#   logs        Tail tmp/deploy.log.
#   cron        Print the cron line that deploys on a schedule.
#
# Options: --repo=owner/name --branch=name --node=/path/node --mode=passenger
#          --install --no-install --no-restart --force --quiet --dry-run
#
# Generated by: noderyx cpanel:deploy-script

set -uo pipefail

# A deploy rewrites this file while bash is still reading it, which would make
# the shell resume at a byte offset in the new contents. Run from a copy.
if [ -z "${NODERYX_RELAUNCHED:-}" ]; then
  __self="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
  __copy="${TMPDIR:-/tmp}/noderyx-deploy-$$.sh"
  if cp "$__self" "$__copy" 2>/dev/null; then
    NODERYX_RELAUNCHED=1 NODERYX_SELF="$__self" bash "$__copy" "$@"
    __status=$?
    rm -f "$__copy"
    exit $__status
  fi
fi

SELF="${NODERYX_SELF:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")}"
DEPLOY_DIR="$(cd "$(dirname "$SELF")" && pwd)"
APP_DIR="$(cd "$DEPLOY_DIR/.." && pwd)"
STATE_DIR="${NODERYX_STATE:-$HOME/.noderyx}"
LOG_FILE="$APP_DIR/tmp/deploy.log"
STAMP="$(date '+%Y%m%d-%H%M%S')"

# Defaults baked in at build time. deploy.config overrides them, the
# environment overrides that, and flags win over everything.
REPOSITORY="webscepts123/Noderyx-Framework"
BRANCH="main"
MODE="passenger"
NODE_BIN=""
GITHUB_TOKEN=""
APP_HOST="127.0.0.1"
APP_PORT="3000"
INSTALL="auto"
RESTART=1
QUIET=0
FORCE=0
DRY_RUN=0
BACKUPS=3
KEEP=()

# Server-owned settings. This file is never replaced by a deploy.
if [ -f "$DEPLOY_DIR/deploy.config" ]; then
  # shellcheck source=/dev/null
  . "$DEPLOY_DIR/deploy.config"
fi

REPOSITORY="${NODERYX_REPOSITORY:-$REPOSITORY}"
BRANCH="${NODERYX_BRANCH:-$BRANCH}"
GITHUB_TOKEN="${NODERYX_GITHUB_TOKEN:-$GITHUB_TOKEN}"

PRESERVE=(
  ".env"
  ".htaccess"
  "tmp/"
  "node_modules/"
  "deployment/deploy.config"
  "noderyx-install.php"
  "noderyx-deploy.php"
  "noderyx-check.php"
  "cgi-bin/"
  ".well-known/"
  "storage/"
  "public/uploads/"
)
SKIP=(
  ".git/"
  ".github/"
  ".vscode/"
  "platforms/"
)

COMMAND="deploy"
for argument in "$@"; do
  case "$argument" in
    --repo=*) REPOSITORY="${argument#*=}" ;;
    --branch=*) BRANCH="${argument#*=}" ;;
    --node=*) NODE_BIN="${argument#*=}" ;;
    --mode=*) MODE="${argument#*=}" ;;
    --token=*) GITHUB_TOKEN="${argument#*=}" ;;
    --install) INSTALL="always" ;;
    --no-install) INSTALL="never" ;;
    --no-restart) RESTART=0 ;;
    --force) FORCE=1 ;;
    --dry-run) DRY_RUN=1 ;;
    --quiet|-q) QUIET=1 ;;
    -h|--help) COMMAND="help" ;;
    --*) echo "Unknown option: $argument" >&2; exit 2 ;;
    *) COMMAND="$argument" ;;
  esac
done

mkdir -p "$APP_DIR/tmp" 2>/dev/null || true
mkdir -p "$STATE_DIR" 2>/dev/null && chmod 700 "$STATE_DIR" 2>/dev/null

say() {
  [ "$QUIET" = "1" ] || printf '%s\n' "$*"
}

log() {
  printf '%s %s\n' "$(date '+%F %T')" "$*" >> "$LOG_FILE" 2>/dev/null || true
  say "$*"
}

fail() {
  printf '%s error: %s\n' "$(date '+%F %T')" "$*" >> "$LOG_FILE" 2>/dev/null || true
  printf 'error: %s\n' "$*" >&2
  exit 1
}

# ---------------------------------------------------------------------------
# Environment
# ---------------------------------------------------------------------------

find_node() {
  if [ -n "$NODE_BIN" ] && [ -x "$NODE_BIN" ]; then
    return 0
  fi
  for candidate in "/opt/alt/alt-nodejs22/root/usr/bin/node" "/opt/alt/alt-nodejs20/root/usr/bin/node" "/opt/cpanel/ea-nodejs22/bin/node" "/opt/cpanel/ea-nodejs20/bin/node" "/usr/local/bin/node" "/usr/bin/node"; do
    if [ -x "$candidate" ]; then
      NODE_BIN="$candidate"
      return 0
    fi
  done
  NODE_BIN="$(command -v node 2>/dev/null || true)"
  [ -n "$NODE_BIN" ]
}

# npm is usually absent from the login PATH even where Node exists, so look
# beside the binary before trusting the shell.
find_npm() {
  NPM_BIN=""
  if [ -n "${NODE_BIN:-}" ] && [ -x "$(dirname "$NODE_BIN")/npm" ]; then
    NPM_BIN="$(dirname "$NODE_BIN")/npm"
    return 0
  fi
  NPM_BIN="$(command -v npm 2>/dev/null || true)"
  [ -n "$NPM_BIN" ]
}

require_repository() {
  if [ -z "$REPOSITORY" ]; then
    fail "No repository set. Run: bash $SELF init"
  fi
  if ! printf '%s' "$REPOSITORY" | grep -Eq '^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$'; then
    fail "Repository must be owner/name, not '$REPOSITORY'."
  fi
}

remote_url() {
  if [ -n "$GITHUB_TOKEN" ]; then
    printf 'https://x-access-token:%s@github.com/%s.git' "$GITHUB_TOKEN" "$REPOSITORY"
  else
    printf 'https://github.com/%s.git' "$REPOSITORY"
  fi
}

# One deploy at a time: cron and a hand-run deploy must not interleave.
LOCK_DIR="$STATE_DIR/deploy.lock"
lock() {
  if ! mkdir "$LOCK_DIR" 2>/dev/null; then
    if [ -f "$LOCK_DIR/pid" ] && ! kill -0 "$(cat "$LOCK_DIR/pid" 2>/dev/null)" 2>/dev/null; then
      rm -rf "$LOCK_DIR"
      mkdir "$LOCK_DIR" 2>/dev/null || fail "Another deploy is running."
    else
      fail "Another deploy is running. Delete $LOCK_DIR if that is wrong."
    fi
  fi
  echo $$ > "$LOCK_DIR/pid"
  trap 'rm -rf "$LOCK_DIR"' EXIT INT TERM
}

# ---------------------------------------------------------------------------
# Fetching
# ---------------------------------------------------------------------------

RELEASE_DIR=""
REVISION="unknown"

fetch_with_git() {
  RELEASE_DIR="$STATE_DIR/repo"
  local url
  url="$(remote_url)"

  if [ -d "$RELEASE_DIR/.git" ]; then
    git -C "$RELEASE_DIR" remote set-url origin "$url" 2>/dev/null
    git -C "$RELEASE_DIR" fetch --depth=1 --quiet origin "$BRANCH" || fail "git fetch failed for $REPOSITORY@$BRANCH."
    git -C "$RELEASE_DIR" checkout --quiet -B "$BRANCH" "origin/$BRANCH" || fail "git checkout failed for $BRANCH."
    git -C "$RELEASE_DIR" reset --hard --quiet "origin/$BRANCH"
    git -C "$RELEASE_DIR" clean -qfd
  else
    rm -rf "$RELEASE_DIR"
    git clone --depth=1 --quiet --branch "$BRANCH" "$url" "$RELEASE_DIR" \
      || fail "git clone failed. Check the repository, the branch, and the token for a private repository."
  fi

  chmod 700 "$RELEASE_DIR" 2>/dev/null
  REVISION="$(git -C "$RELEASE_DIR" rev-parse --short HEAD 2>/dev/null || echo unknown)"
}

# No git on the account: take the branch tarball, the same source the browser
# deploy panel uses.
fetch_with_archive() {
  local work="$STATE_DIR/work-$STAMP"
  local archive="$work/branch.tar.gz"
  local url="https://codeload.github.com/$REPOSITORY/tar.gz/refs/heads/$BRANCH"

  rm -rf "$work"
  mkdir -p "$work" || fail "Cannot write to $STATE_DIR."

  if command -v curl >/dev/null 2>&1; then
    if [ -n "$GITHUB_TOKEN" ]; then
      curl -fsSL -H "Authorization: Bearer $GITHUB_TOKEN" -o "$archive" "$url" || fail "Download failed: $url"
    else
      curl -fsSL -o "$archive" "$url" || fail "Download failed: $url"
    fi
  elif command -v wget >/dev/null 2>&1; then
    if [ -n "$GITHUB_TOKEN" ]; then
      wget -q --header="Authorization: Bearer $GITHUB_TOKEN" -O "$archive" "$url" || fail "Download failed: $url"
    else
      wget -q -O "$archive" "$url" || fail "Download failed: $url"
    fi
  else
    fail "No git, curl, or wget on this account. Use noderyx-deploy.php in a browser instead."
  fi

  tar -xzf "$archive" -C "$work" || fail "The archive could not be unpacked."
  rm -f "$archive"

  # GitHub wraps the tree in <repo>-<branch>/.
  local inner
  inner="$(find "$work" -mindepth 1 -maxdepth 1 -type d | head -n 1)"
  [ -n "$inner" ] || fail "The archive was empty."
  RELEASE_DIR="$inner"
  REVISION="$BRANCH-archive"
}

prepare_release() {
  if command -v git >/dev/null 2>&1; then
    fetch_with_git
  else
    fetch_with_archive
  fi

  if [ ! -f "$RELEASE_DIR/package.json" ] && [ "$FORCE" != "1" ]; then
    fail "$REPOSITORY@$BRANCH has no package.json at its root. Use --force to deploy it anyway."
  fi
}

cleanup_release() {
  case "$RELEASE_DIR" in
    "$STATE_DIR"/work-*) rm -rf "$(dirname "$RELEASE_DIR")" ;;
  esac
  rm -rf "$STATE_DIR"/work-* 2>/dev/null
}

# ---------------------------------------------------------------------------
# Applying
# ---------------------------------------------------------------------------

# Every protected path, as a list of paths relative to the application root.
# KEEP is expanded the long way so an empty array does not trip set -u on the
# bash 4.2 that older CloudLinux images still ship.
protected_paths() {
  printf '%s\n' "${PRESERVE[@]}" ${KEEP[@]+"${KEEP[@]}"} "${SKIP[@]}"
}

is_preserved() {
  local candidate="$1" path
  while read -r path; do
    [ "${path%/}" = "$candidate" ] && return 0
  done < <(protected_paths)
  return 1
}

# True when something below this directory is protected, so the directory has
# to be copied entry by entry rather than replaced wholesale.
holds_preserved() {
  local candidate="$1" path
  while read -r path; do
    case "${path%/}" in "$candidate"/*) return 0 ;; esac
  done < <(protected_paths)
  return 1
}

backup_current() {
  BACKUP_DIR="$STATE_DIR/backups/$STAMP"
  mkdir -p "$BACKUP_DIR" || return 0
  # node_modules is large and reinstallable; tmp/ is runtime state. Neither is
  # copied in the first place: disk I/O is the scarce resource on these plans.
  if command -v rsync >/dev/null 2>&1; then
    rsync -a --exclude=/node_modules/ --exclude=/tmp/ "$APP_DIR/" "$BACKUP_DIR/" 2>/dev/null
  else
    local entry base
    shopt -s dotglob nullglob
    for entry in "$APP_DIR"/*; do
      base="$(basename "$entry")"
      case "$base" in node_modules|tmp) continue ;; esac
      cp -a "$entry" "$BACKUP_DIR/" 2>/dev/null
    done
    shopt -u dotglob nullglob
  fi
  # Keep the newest few so a rollback is possible without filling the quota.
  ls -1dt "$STATE_DIR/backups"/*/ 2>/dev/null | tail -n +$((BACKUPS + 1)) | while read -r old; do
    rm -rf "$old"
  done
}

sync_release() {
  local excludes=() path
  for path in "${PRESERVE[@]}" ${KEEP[@]+"${KEEP[@]}"} "${SKIP[@]}"; do
    excludes+=("--exclude=/$path")
  done
  # A branch without its own deployment/ must not delete this script.
  [ -d "$RELEASE_DIR/deployment" ] || excludes+=("--exclude=/deployment/")

  if command -v rsync >/dev/null 2>&1; then
    local flags=(-a --delete)
    [ "$DRY_RUN" = "1" ] && flags+=(--dry-run --itemize-changes)
    rsync "${flags[@]}" "${excludes[@]}" "$RELEASE_DIR/" "$APP_DIR/" \
      || fail "rsync failed. Check the permissions on $APP_DIR."
    return 0
  fi

  # Without rsync, files deleted from the branch stay behind; everything else
  # is still replaced, so the deploy is applied rather than refused.
  log "rsync is missing: copying instead, so files removed from the branch stay on disk."
  local entry base
  shopt -s dotglob nullglob
  for entry in "$RELEASE_DIR"/*; do
    base="$(basename "$entry")"
    copy_tree "$entry" "$APP_DIR/$base" "$base"
  done
  shopt -u dotglob nullglob
}

# Replace one path, descending only where a protected path sits underneath.
# deployment/ is the case that matters: deploy.sh must follow the branch while
# deploy.config stays exactly as this account wrote it.
copy_tree() {
  local source="$1" destination="$2" path="$3" entry base
  is_preserved "$path" && return 0

  if [ -d "$source" ] && holds_preserved "$path"; then
    mkdir -p "$destination" || fail "Cannot create $destination."
    shopt -s dotglob nullglob
    for entry in "$source"/*; do
      base="$(basename "$entry")"
      copy_tree "$entry" "$destination/$base" "$path/$base"
    done
    shopt -u dotglob nullglob
    return 0
  fi

  if [ "$DRY_RUN" = "1" ]; then
    say "would copy $path"
    return 0
  fi
  rm -rf "$destination"
  cp -a "$source" "$destination" || fail "Cannot write $path into $APP_DIR."
}

# ---------------------------------------------------------------------------
# Dependencies and restart
# ---------------------------------------------------------------------------

dependency_fingerprint() {
  cat "$APP_DIR/package.json" "$APP_DIR/package-lock.json" 2>/dev/null | cksum | awk '{print $1 "-" $2}'
}

install_dependencies() {
  [ -f "$APP_DIR/package.json" ] || return 0
  if [ "$INSTALL" = "never" ]; then
    say "Skipping dependencies (--no-install)."
    return 0
  fi

  local fingerprint stored
  fingerprint="$(dependency_fingerprint)"
  stored="$(cat "$STATE_DIR/dependencies.txt" 2>/dev/null || true)"
  if [ "$INSTALL" != "always" ] && [ "$fingerprint" = "$stored" ] && [ -d "$APP_DIR/node_modules" ]; then
    say "Dependencies unchanged."
    return 0
  fi

  if ! find_node || ! find_npm; then
    log "npm was not found, so dependencies were not installed. Upload node_modules, or set NODE_BIN in deploy.config."
    return 0
  fi

  local command="install"
  [ -f "$APP_DIR/package-lock.json" ] && command="ci"
  say "Running npm $command."
  if [ "$DRY_RUN" = "1" ]; then
    return 0
  fi

  if (cd "$APP_DIR" && PATH="$(dirname "$NODE_BIN"):$PATH" "$NPM_BIN" "$command" --omit=dev --no-audit --no-fund >> "$LOG_FILE" 2>&1); then
    printf '%s' "$fingerprint" > "$STATE_DIR/dependencies.txt"
    log "Dependencies installed with npm $command."
  else
    # npm ci refuses a lockfile that drifted from package.json; install copes.
    if [ "$command" = "ci" ] && (cd "$APP_DIR" && PATH="$(dirname "$NODE_BIN"):$PATH" "$NPM_BIN" install --omit=dev --no-audit --no-fund >> "$LOG_FILE" 2>&1); then
      printf '%s' "$fingerprint" > "$STATE_DIR/dependencies.txt"
      log "Dependencies installed with npm install after npm ci failed."
    else
      fail "npm $command failed. The last lines of tmp/deploy.log say why."
    fi
  fi
}

restart_app() {
  if [ "$RESTART" != "1" ] || [ "$DRY_RUN" = "1" ]; then
    return 0
  fi
  if [ "$MODE" = "proxy" ]; then
    [ -f "$APP_DIR/noderyx-stop.sh" ] && bash "$APP_DIR/noderyx-stop.sh" >/dev/null 2>&1
    if [ -f "$APP_DIR/noderyx-start.sh" ]; then
      find_node
      NODERYX_NODE="${NODE_BIN:-}" HOST="$APP_HOST" PORT="$APP_PORT" bash "$APP_DIR/noderyx-start.sh"
      log "Restarted the Node process on $APP_HOST:$APP_PORT."
      return 0
    fi
    log "noderyx-start.sh is missing, so nothing was restarted."
    return 0
  fi
  # Passenger reloads on the next request when this file changes. It is also
  # what "Setup Node.js App" watches, so managed applications restart too.
  mkdir -p "$APP_DIR/tmp"
  date '+%F %T' > "$APP_DIR/tmp/restart.txt"
  log "Touched tmp/restart.txt; the next request reloads the application."
}

run_hook() {
  [ -f "$DEPLOY_DIR/after-deploy.sh" ] || return 0
  [ "$DRY_RUN" = "1" ] && return 0
  say "Running deployment/after-deploy.sh."
  (cd "$APP_DIR" && NODERYX_APP_DIR="$APP_DIR" NODE_BIN="${NODE_BIN:-}" bash "$DEPLOY_DIR/after-deploy.sh") \
    || log "after-deploy.sh exited non-zero; the deploy itself succeeded."
}

# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

command_deploy() {
  require_repository
  lock

  log "Deploying $REPOSITORY@$BRANCH into $APP_DIR."
  prepare_release
  log "Fetched $REVISION."

  [ "$DRY_RUN" = "1" ] || backup_current
  sync_release
  cleanup_release

  if [ "$DRY_RUN" = "1" ]; then
    say "Dry run: nothing was written."
    return 0
  fi

  install_dependencies
  restart_app
  run_hook

  printf '%s %s@%s (%s)\n' "$(date '+%F %T')" "$REPOSITORY" "$BRANCH" "$REVISION" > "$APP_DIR/tmp/last-deploy.txt"
  log "Deployed $REPOSITORY@$BRANCH ($REVISION)."
}

command_init() {
  local target="$DEPLOY_DIR/deploy.config"
  if [ -f "$target" ] && [ "$FORCE" != "1" ]; then
    fail "$target already exists. Edit it, or pass --force to replace it."
  fi
  cat > "$target" <<CONFIG
# Noderyx deploy settings for this account.
# A deploy never replaces this file, so it is the right place for anything
# that belongs to this server rather than to the repository.

REPOSITORY="$REPOSITORY"
BRANCH="$BRANCH"
MODE="$MODE"

# Leave empty to detect the Node binary automatically.
NODE_BIN="${NODE_BIN:-}"

# Fine-grained personal access token with read access to the repository.
# Only needed for a private repository. Keep this file at chmod 600.
GITHUB_TOKEN=""

# auto installs only when package.json changed; always or never override that.
INSTALL="auto"

# Extra paths this deploy must not replace, relative to the application root.
KEEP=()
CONFIG
  chmod 600 "$target"
  say "Wrote $target. Set REPOSITORY, then run: bash $SELF"
}

command_status() {
  find_node || true
  find_npm || true
  printf 'Application  %s\n' "$APP_DIR"
  printf 'Repository   %s\n' "${REPOSITORY:-(not set)}"
  printf 'Branch       %s\n' "$BRANCH"
  printf 'Mode         %s\n' "$MODE"
  printf 'Node         %s\n' "${NODE_BIN:-(not found)}"
  printf 'npm          %s\n' "${NPM_BIN:-(not found)}"
  printf 'git          %s\n' "$(command -v git 2>/dev/null || echo '(not found; uses the branch tarball)')"
  printf 'rsync        %s\n' "$(command -v rsync 2>/dev/null || echo '(not found; copies without deleting)')"
  printf 'Config       %s\n' "$([ -f "$DEPLOY_DIR/deploy.config" ] && echo "$DEPLOY_DIR/deploy.config" || echo '(none; using built-in defaults)')"
  printf 'Last deploy  %s\n' "$(cat "$APP_DIR/tmp/last-deploy.txt" 2>/dev/null || echo 'never')"
  printf 'Snapshots    %s\n' "$(ls -1d "$STATE_DIR/backups"/*/ 2>/dev/null | wc -l | tr -d ' ')"
}

command_rollback() {
  local latest
  latest="$(ls -1dt "$STATE_DIR/backups"/*/ 2>/dev/null | head -n 1)"
  [ -n "$latest" ] || fail "No snapshot to roll back to."
  lock
  log "Rolling back to $latest."
  if command -v rsync >/dev/null 2>&1; then
    rsync -a --delete --exclude=/node_modules/ --exclude=/tmp/ "$latest" "$APP_DIR/" || fail "Rollback failed."
  else
    cp -a "$latest/." "$APP_DIR/" || fail "Rollback failed."
  fi
  restart_app
  log "Rolled back to $latest."
}

command_cron() {
  printf 'cPanel > Cron Jobs > Add New Cron Job, once every 30 minutes:\n\n'
  printf '  */30 * * * * /bin/bash "$HOME/public_html/deployment/deploy.sh" --quiet >/dev/null 2>&1\n\n'
  printf 'Deploys only replace files that changed, so a run with nothing new is cheap.\n'
}

command_help() {
  sed -n '2,40p' "$SELF" | sed 's/^# \{0,1\}//'
}

case "$COMMAND" in
  deploy) command_deploy ;;
  init) command_init ;;
  status) command_status ;;
  install) find_node || true; INSTALL="always"; install_dependencies ;;
  restart) restart_app ;;
  rollback) command_rollback ;;
  logs) tail -n 50 "$LOG_FILE" 2>/dev/null || echo "No deploys yet." ;;
  cron) command_cron ;;
  help) command_help ;;
  *) fail "Unknown command: $COMMAND. Try: deploy, init, status, install, restart, rollback, logs, cron." ;;
esac
