import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";
import { noderyxIcon } from "./icons.js";
import { buildMobile, mobileOptions, webDirectory } from "./mobile.js";

/**
 * The packaged app serves its bundle from this private origin, the desktop
 * counterpart of capacitor://localhost. API servers must allow it for CORS.
 */
export const DESKTOP_SCHEME = "noderyx";
export const DESKTOP_ORIGIN = `${DESKTOP_SCHEME}://app`;

export const DESKTOP_TARGETS = {
  windows: { flag: "--win", host: "win32", label: "Windows" },
  mac: { flag: "--mac", host: "darwin", label: "macOS" },
  linux: { flag: "--linux", host: "linux", label: "Linux" }
};

export const DESKTOP_DEFAULTS = {
  out: "platforms/desktop",
  // Null takes the version from the project's package.json.
  version: null,
  window: {
    width: 1200,
    height: 800,
    minWidth: 720,
    minHeight: 480,
    resizable: true,
    // Remember size, position, and maximized state between launches.
    rememberBounds: true
  },
  singleInstance: true,
  // Null enables developer tools only when the app is not packaged.
  devTools: null,
  // Browser permissions the window may grant. Everything else is denied.
  permissions: ["notifications", "clipboard-sanitized-write", "fullscreen"],
  liveReloadUrl: null,
  // The mobile remote UI targets phones, so desktop builds opt in separately.
  remoteUi: false,
  windows: { targets: ["nsis"] },
  mac: { targets: ["dmg", "zip"], category: "public.app-category.productivity" },
  linux: { targets: ["AppImage"], category: "Utility" }
};

// Shared with the mobile block, so one project describes its app once.
const SHARED_FIELDS = ["appId", "appName", "views", "public", "entry", "apiUrl", "data", "pages", "exclude", "description", "pwa"];

function packageName(appName) {
  return appName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "") || "noderyx-app";
}

/**
 * Resolve the `desktop` block. Anything it does not set (app ID, name, views,
 * API URL, render data) falls back to the `mobile` block.
 */
export function desktopOptions(config = {}, overrides = {}) {
  const provided = Object.fromEntries(
    Object.entries(overrides).filter(([, value]) => value !== undefined)
  );
  const { apps: _apps, ...mobile } = config.mobile ?? {};
  const desktop = config.desktop ?? {};
  const shared = Object.fromEntries(SHARED_FIELDS
    .filter((field) => mobile[field] !== undefined)
    .map((field) => [field, mobile[field]]));

  const options = {
    ...DESKTOP_DEFAULTS,
    ...shared,
    ...desktop,
    ...provided,
    window: { ...DESKTOP_DEFAULTS.window, ...(desktop.window ?? {}), ...(provided.window ?? {}) },
    windows: { ...DESKTOP_DEFAULTS.windows, ...(desktop.windows ?? {}) },
    mac: { ...DESKTOP_DEFAULTS.mac, ...(desktop.mac ?? {}) },
    linux: { ...DESKTOP_DEFAULTS.linux, ...(desktop.linux ?? {}) }
  };
  if (options.liveReloadUrl && !/^https?:\/\//.test(options.liveReloadUrl)) {
    throw new Error(`Invalid desktop.liveReloadUrl: ${options.liveReloadUrl} (use http:// or https://)`);
  }

  // The web bundle is the mobile bundle with a different output folder, so the
  // same validation (reverse-domain app ID, PWA colors) applies.
  options.webConfig = { ...config, mobile: { ...shared, ...pick(desktop, SHARED_FIELDS) } };
  options.webOverrides = {
    ...pick(provided, SHARED_FIELDS),
    out: options.out,
    remoteUi: options.remoteUi,
    app: null,
    capacitor: false
  };
  options.web = mobileOptions(options.webConfig, options.webOverrides);
  options.appId = options.web.appId;
  options.appName = options.web.appName;
  return options;
}

function pick(source, fields) {
  return Object.fromEntries(fields.filter((field) => source[field] !== undefined).map((field) => [field, source[field]]));
}

async function projectVersion() {
  try {
    return JSON.parse(await readFile(resolve("package.json"), "utf8")).version ?? "1.0.0";
  } catch {
    return "1.0.0";
  }
}

/** The settings baked into the generated main process. */
export function runtimeConfig(options) {
  return {
    appId: options.appId,
    appName: options.appName,
    scheme: DESKTOP_SCHEME,
    window: options.window,
    backgroundColor: options.web.pwa.backgroundColor,
    singleInstance: options.singleInstance,
    devTools: options.devTools,
    permissions: options.permissions,
    liveReloadUrl: options.liveReloadUrl
  };
}

/**
 * Electron's main process. It serves the bundle from a private, secure origin,
 * keeps the renderer sandboxed with no Node access, and sends every link that
 * leaves the app to the system browser.
 */
export function mainProcess(options) {
  return `// Generated by Noderyx build:desktop. Do not edit: change \`desktop\` in
// noderyx.config.js and rebuild.
"use strict";
const { app, BrowserWindow, Menu, net, protocol, screen, session, shell } = require("electron");
const { existsSync, readFileSync, statSync, writeFileSync } = require("node:fs");
const path = require("node:path");
const { pathToFileURL } = require("node:url");

const CONFIG = ${JSON.stringify(runtimeConfig(options), null, 2)};
const ORIGIN = \`\${CONFIG.scheme}://app\`;
const WWW = path.join(__dirname, "www");
const IS_MAC = process.platform === "darwin";

// A standard, secure scheme gives the bundle a real origin, so fetch, storage,
// and the service worker behave as they do on the web.
protocol.registerSchemesAsPrivileged([{
  scheme: CONFIG.scheme,
  privileges: { standard: true, secure: true, supportFetchAPI: true, allowServiceWorkers: true, corsEnabled: true, stream: true }
}]);

if (process.platform === "win32") app.setAppUserModelId(CONFIG.appId);
if (CONFIG.singleInstance && !app.requestSingleInstanceLock()) app.quit();

function bundleFile(requestUrl) {
  const relativePath = decodeURIComponent(new URL(requestUrl).pathname).replace(/^\\/+/, "");
  // Files ship inside the app, so a service worker would only serve stale
  // copies after an update. Refusing it makes the registration a no-op.
  if (relativePath === "sw.js") return null;
  const file = path.resolve(WWW, relativePath);
  if (file !== WWW && !file.startsWith(WWW + path.sep)) return null;
  if (relativePath && existsSync(file) && statSync(file).isFile()) return file;
  // Clean routes such as /about are drawn by the router from index.html.
  return path.extname(relativePath) ? null : path.join(WWW, "index.html");
}

function isAppUrl(url) {
  if (url.startsWith(\`\${ORIGIN}/\`)) return true;
  return Boolean(CONFIG.liveReloadUrl) && new URL(url).origin === new URL(CONFIG.liveReloadUrl).origin;
}

function openExternal(url) {
  if (/^(https?|mailto):/i.test(url)) shell.openExternal(url);
}

const stateFile = () => path.join(app.getPath("userData"), "window-state.json");

function savedBounds() {
  if (!CONFIG.window.rememberBounds) return {};
  try {
    const state = JSON.parse(readFileSync(stateFile(), "utf8"));
    // Drop a position that is no longer on any connected display.
    const visible = screen.getAllDisplays().some(({ workArea: area }) => state.x < area.x + area.width
      && state.x + state.width > area.x && state.y < area.y + area.height && state.y + state.height > area.y);
    return visible ? state : { width: state.width, height: state.height, maximized: state.maximized };
  } catch {
    return {};
  }
}

function rememberBounds(window) {
  if (!CONFIG.window.rememberBounds) return;
  try {
    writeFileSync(stateFile(), JSON.stringify({ ...window.getNormalBounds(), maximized: window.isMaximized() }));
  } catch {}
}

function createWindow() {
  const { maximized, ...bounds } = savedBounds();
  const { rememberBounds: _remember, ...size } = CONFIG.window;
  const window = new BrowserWindow({
    ...size,
    ...bounds,
    title: CONFIG.appName,
    backgroundColor: CONFIG.backgroundColor,
    show: false,
    autoHideMenuBar: !IS_MAC,
    icon: path.join(__dirname, "build", "icon.png"),
    webPreferences: {
      preload: path.join(__dirname, "preload.cjs"),
      contextIsolation: true,
      sandbox: true,
      nodeIntegration: false,
      webSecurity: true,
      devTools: CONFIG.devTools ?? !app.isPackaged
    }
  });

  window.once("ready-to-show", () => {
    if (maximized) window.maximize();
    window.show();
  });
  window.on("close", () => rememberBounds(window));
  window.webContents.setWindowOpenHandler(({ url }) => {
    openExternal(url);
    return { action: "deny" };
  });
  window.webContents.on("will-navigate", (event, url) => {
    if (isAppUrl(url)) return;
    event.preventDefault();
    openExternal(url);
  });
  window.loadURL(CONFIG.liveReloadUrl ?? \`\${ORIGIN}/\`);
  return window;
}

function applicationMenu() {
  const devTools = CONFIG.devTools ?? !app.isPackaged;
  return Menu.buildFromTemplate([
    ...(IS_MAC ? [{ role: "appMenu" }] : []),
    { role: "fileMenu" },
    { role: "editMenu" },
    {
      label: "View",
      submenu: [
        { role: "reload" },
        ...(devTools ? [{ role: "toggleDevTools" }] : []),
        { type: "separator" },
        { role: "resetZoom" },
        { role: "zoomIn" },
        { role: "zoomOut" },
        { type: "separator" },
        { role: "togglefullscreen" }
      ]
    },
    { role: "windowMenu" }
  ]);
}

app.on("second-instance", () => {
  const [window] = BrowserWindow.getAllWindows();
  if (!window) return;
  if (window.isMinimized()) window.restore();
  window.focus();
});

app.whenReady().then(() => {
  protocol.handle(CONFIG.scheme, (request) => {
    const file = bundleFile(request.url);
    return file ? net.fetch(pathToFileURL(file).toString()) : new Response("Not found", { status: 404 });
  });
  session.defaultSession.setPermissionRequestHandler((_contents, permission, allow) => {
    allow(CONFIG.permissions.includes(permission));
  });
  Menu.setApplicationMenu(applicationMenu());
  createWindow();
  app.on("activate", () => {
    if (!BrowserWindow.getAllWindows().length) createWindow();
  });
});

app.on("window-all-closed", () => {
  if (!IS_MAC) app.quit();
});
`;
}

/**
 * The only thing the page learns about its host. The renderer is sandboxed,
 * so this exposes plain values, never Node or Electron APIs.
 */
export function preloadScript(options, version) {
  return `// Generated by Noderyx build:desktop.
"use strict";
const { contextBridge } = require("electron");

const platform = process.platform === "darwin" ? "macos" : process.platform === "win32" ? "windows" : "linux";

contextBridge.exposeInMainWorld("NoderyxDesktop", Object.freeze({
  platform,
  appId: ${JSON.stringify(options.appId)},
  appName: ${JSON.stringify(options.appName)},
  version: ${JSON.stringify(version)}
}));
`;
}

/** electron-builder settings: NSIS installer on Windows, DMG on macOS. */
export function builderConfig(options) {
  return {
    appId: options.appId,
    productName: options.appName,
    directories: { output: "dist", buildResources: "build" },
    files: ["main.cjs", "preload.cjs", "www/**/*", "package.json"],
    win: { target: options.windows.targets, icon: "build/icon.png" },
    nsis: { oneClick: false, perMachine: false, allowToChangeInstallationDirectory: true },
    mac: {
      target: options.mac.targets,
      category: options.mac.category,
      icon: "build/icon.png",
      hardenedRuntime: true
    },
    linux: { target: options.linux.targets, category: options.linux.category, icon: "build/icon.png" }
  };
}

/**
 * The desktop project's package.json. Fields Noderyx owns are rewritten on
 * every build; dependencies and anything else the project added are kept.
 */
export function desktopPackage(options, version, existing = {}) {
  return {
    ...existing,
    name: packageName(options.appName),
    productName: options.appName,
    version,
    description: options.web.pwa.description ?? `${options.appName} desktop app`,
    author: existing.author ?? options.appName,
    private: true,
    main: "main.cjs",
    scripts: {
      ...(existing.scripts ?? {}),
      start: "electron .",
      "dist:windows": "electron-builder --win",
      "dist:mac": "electron-builder --mac",
      "dist:linux": "electron-builder --linux"
    },
    build: builderConfig(options)
  };
}

/**
 * Compile the views into the same self-contained bundle the mobile build
 * produces, then write the Electron project around it.
 */
export async function buildDesktop(config = {}, overrides = {}, log = console.log) {
  const options = desktopOptions(config, overrides);
  const root = resolve(options.out);
  const version = options.version ?? await projectVersion();

  const { pages, assets } = await buildMobile(options.webConfig, options.webOverrides, () => {});

  const manifestPath = join(root, "package.json");
  const existing = existsSync(manifestPath) ? JSON.parse(await readFile(manifestPath, "utf8")) : {};
  await writeFile(manifestPath, `${JSON.stringify(desktopPackage(options, version, existing), null, 2)}\n`);
  await writeFile(join(root, "main.cjs"), mainProcess(options));
  await writeFile(join(root, "preload.cjs"), preloadScript(options, version));

  // electron-builder turns one large PNG into .ico and .icns.
  await mkdir(join(root, "build"), { recursive: true });
  const icon = join(root, "build/icon.png");
  if (!existsSync(icon)) await writeFile(icon, noderyxIcon(1024));

  log(`Built desktop app with ${pages.length} page${pages.length === 1 ? "" : "s"} and ${assets} asset${assets === 1 ? "" : "s"} into ${relative(process.cwd(), root) || root}`);
  log(`App ID: ${options.appId}   Version: ${version}${options.web.apiUrl ? `   API: ${options.web.apiUrl}` : ""}`);
  return { root, www: resolve(webDirectory(options.web)), pages, assets, version, options };
}

/** A GitHub Actions workflow that packages Windows and macOS on their own runners. */
export function desktopWorkflow(options) {
  const out = options.out.replaceAll("\\", "/");
  return `# Generated by Noderyx desktop:workflow.
# Builds the Windows installer and the macOS disk image on native runners.
# Run it from the Actions tab, or push a tag such as v1.0.0.
name: Desktop apps

on:
  workflow_dispatch:
  push:
    tags: ["v*"]

jobs:
  package:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: windows
          - os: macos-latest
            target: mac
    runs-on: \${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npx noderyx-framework desktop:init
      - run: npx noderyx-framework desktop:package \${{ matrix.target }}
        env:
          # Add these secrets to sign and notarize. Unsigned builds still work.
          CSC_LINK: \${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: \${{ secrets.CSC_KEY_PASSWORD }}
          APPLE_ID: \${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: \${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: \${{ secrets.APPLE_TEAM_ID }}
          CSC_IDENTITY_AUTO_DISCOVERY: \${{ secrets.CSC_LINK != '' }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${packageName(options.appName)}-\${{ matrix.target }}
          path: |
            ${out}/dist/*.exe
            ${out}/dist/*.dmg
            ${out}/dist/*.zip
          if-no-files-found: error
`;
}
