const VOID = new Set(["meta", "link", "input", "img", "br", "hr", "source"]);

function attributes(source) {
  const result = {};
  for (const match of source.matchAll(/([^\s=]+)(?:="([^"]*)")?/g)) {
    result[match[1]] = match[2] ?? "";
  }
  return result;
}

/** Compile rendered web markup into Noderyx's structured mobile-page format. */
export function compileMNodeFrame(html, route = "") {
  const root = { tag: "#document", children: [] };
  const stack = [root];
  const tokens = String(html).replace(/<!doctype[^>]*>/i, "").match(/<[^>]+>|[^<]+/g) ?? [];

  for (const token of tokens) {
    if (token.startsWith("<!--")) continue;
    if (token.startsWith("</")) {
      if (stack.length > 1) stack.pop();
      continue;
    }
    if (token.startsWith("<")) {
      const match = token.match(/^<([\w-]+)([^>]*)>/);
      if (!match) continue;
      const node = { tag: match[1].toLowerCase(), attrs: attributes(match[2]), children: [] };
      stack[stack.length - 1].children.push(node);
      if (!VOID.has(node.tag) && !token.endsWith("/>")) stack.push(node);
      continue;
    }
    if (token) stack[stack.length - 1].children.push(token);
  }

  const payload = {
    generated: "Do not edit this file. Edit resources/views/*.noderframe and rebuild.",
    format: "mnoderframe",
    version: 1,
    route,
    document: root.children
  };

  return `MNF1\n${JSON.stringify(payload, null, 2)}\n`;
}

export function parseMNodeFrame(source) {
  if (!String(source).startsWith("MNF1\n")) throw new SyntaxError("Invalid .mnoderframe payload");
  const payload = JSON.parse(String(source).slice(5));
  if (payload?.format !== "mnoderframe" || payload.version !== 1 || !Array.isArray(payload.document)) {
    throw new SyntaxError("Unsupported .mnoderframe payload");
  }
  return payload;
}
