// Progressive web app layer. The same manifest, service worker, and head tags
// are used by the Noderyx server and by the static bundle that Capacitor wraps
// into Android and iOS applications.

export const PWA_DEFAULTS = {
  name: "Noderyx App",
  shortName: null,
  description: "Built with Noderyx Framework.",
  themeColor: "#090B14",
  backgroundColor: "#090B14",
  display: "standalone",
  orientation: "portrait",
  startUrl: "/",
  scope: "/",
  iconPath: "/public/icons",
  manifestPath: "/manifest.webmanifest",
  serviceWorkerPath: "/sw.js",
  offlinePath: "/offline.html",
  precache: ["/public/cool.css", "/public/noderyx-native.js", "/public/noderyx-router.js"],
  version: "1"
};

export function pwaOptions(overrides = {}) {
  const provided = Object.fromEntries(
    Object.entries(overrides).filter(([, value]) => value !== undefined)
  );
  const options = { ...PWA_DEFAULTS, ...provided };
  options.shortName = options.shortName ?? options.name.slice(0, 12);
  return options;
}

export function manifest(overrides = {}) {
  const options = pwaOptions(overrides);
  return {
    id: options.scope,
    name: options.name,
    short_name: options.shortName,
    description: options.description,
    start_url: options.startUrl,
    scope: options.scope,
    display: options.display,
    display_override: ["standalone", "minimal-ui", "browser"],
    orientation: options.orientation,
    theme_color: options.themeColor,
    background_color: options.backgroundColor,
    icons: [
      { src: `${options.iconPath}/icon-192.png`, sizes: "192x192", type: "image/png", purpose: "any" },
      { src: `${options.iconPath}/icon-512.png`, sizes: "512x512", type: "image/png", purpose: "any" },
      { src: `${options.iconPath}/icon-maskable-512.png`, sizes: "512x512", type: "image/png", purpose: "maskable" }
    ]
  };
}

export function serviceWorker(overrides = {}) {
  const options = pwaOptions(overrides);
  const cacheName = `noderyx-${options.version}`;
  const precache = JSON.stringify([...new Set([options.startUrl, ...options.precache])]);

  return `// Generated by Noderyx Framework. Rebuild with: noderyx build:mobile
const CACHE = ${JSON.stringify(cacheName)};
const PRECACHE = ${precache};
const OFFLINE = ${JSON.stringify(options.offlinePath)};

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    await Promise.allSettled([...PRECACHE, OFFLINE].map((url) => cache.add(url)));
    await self.skipWaiting();
  })());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key !== CACHE) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

self.addEventListener("message", (event) => {
  if (event.data === "noderyx:skip-waiting") self.skipWaiting();
});

// A shared device must not serve one person's pages to the next, so anything
// personalised or explicitly uncacheable is never written to the cache.
function isPrivate(response) {
  const control = response.headers.get("cache-control") ?? "";
  const vary = response.headers.get("vary") ?? "";
  return /no-store|private/i.test(control) || /cookie|authorization/i.test(vary);
}

async function networkFirst(request) {
  const cache = await caches.open(CACHE);
  try {
    const response = await fetch(request);
    if (response.ok && !isPrivate(response)) cache.put(request, response.clone());
    return response;
  } catch (error) {
    const cached = await cache.match(request);
    if (cached) return cached;
    if (request.mode === "navigate") {
      const offline = await cache.match(OFFLINE);
      if (offline) return offline;
    }
    throw error;
  }
}

async function cacheFirst(request) {
  const cache = await caches.open(CACHE);
  const cached = await cache.match(request);
  if (cached) {
    fetch(request).then((response) => {
      if (response.ok && !isPrivate(response)) cache.put(request, response.clone());
    }).catch(() => {});
    return cached;
  }
  const response = await fetch(request);
  if (response.ok && !isPrivate(response)) cache.put(request, response.clone());
  return response;
}

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;
  // Authenticated requests always go to the network.
  if (request.headers.has("authorization")) return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  if (url.pathname.startsWith("/__untitled/")) return;
  if (url.pathname.startsWith("/api/")) return;

  const isAsset = /\\.(css|js|png|jpg|jpeg|svg|webp|woff2?|ico|json)$/.test(url.pathname);
  event.respondWith(isAsset ? cacheFirst(request) : networkFirst(request));
});
`;
}

/**
 * Head tags plus the service worker registration for a Noderyx page.
 */
export function pwaHead(overrides = {}, { skip = [], nonce = "" } = {}) {
  const options = pwaOptions(overrides);
  const attribute = nonce ? ` nonce="${nonce}"` : "";
  return [
    `<link rel="manifest" href="${options.manifestPath}">`,
    skip.includes("theme-color") ? "" : `<meta name="theme-color" content="${options.themeColor}">`,
    `<meta name="color-scheme" content="dark light">`,
    `<meta name="mobile-web-app-capable" content="yes">`,
    `<meta name="apple-mobile-web-app-capable" content="yes">`,
    `<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">`,
    `<meta name="apple-mobile-web-app-title" content="${options.shortName}">`,
    `<link rel="apple-touch-icon" href="${options.iconPath}/apple-touch-icon.png">`,
    `<link rel="icon" href="${options.iconPath}/icon-192.png" sizes="192x192" type="image/png">`,
    `<script src="/public/noderyx-native.js" defer${attribute}></script>`,
    `<script src="/public/noderyx-router.js" defer${attribute}></script>`,
    `<script${attribute}>if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("${options.serviceWorkerPath}").catch(()=>{}));</script>`
  ].filter(Boolean).join("");
}

const VIEWPORT = '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">';

/**
 * Add the mobile head tags to compiled HTML. Existing viewport tags are
 * upgraded with `viewport-fit=cover` so pages can use the safe-area insets.
 */
export function injectPwa(html, overrides = {}, nonce = "") {
  if (typeof html !== "string" || !/<head[\s>]/i.test(html)) return html;
  if (html.includes('rel="manifest"')) return html;

  let output = /<meta[^>]+name="viewport"[^>]*>/i.test(html)
    ? html.replace(/<meta[^>]+name="viewport"[^>]*>/i, VIEWPORT)
    : html.replace(/<head([^>]*)>/i, `<head$1>${VIEWPORT}`);

  const skip = /<meta[^>]+name="theme-color"/i.test(output) ? ["theme-color"] : [];
  const tags = pwaHead(overrides, { skip, nonce });
  return /<\/head>/i.test(output)
    ? output.replace(/<\/head>/i, `${tags}</head>`)
    : output.replace(/<head([^>]*)>/i, `<head$1>${tags}`);
}
